version: '3.7'

networks:
  kong-net:

volumes:
  kong-datastore:
  keycloak-datastore:

services:
  kong-db:
    image: postgres:9.6-alpine
    init: true
    restart: on-failure
    volumes:
      - kong-datastore:/var/lib/postgresql/data
    networks:
      - kong-net
    environment:
      POSTGRES_DB:       kong
      POSTGRES_USER:     kong
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3

  kong-migration:
    image: kong_oidc:1.0-SNAPSHOT
    init: true
    depends_on:
      - kong-db
    command: kong migrations bootstrap
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          kong-db
      KONG_PG_PORT:          5432
      KONG_PG_DATABASE:      kong
      KONG_PG_USER:          kong
      KONG_PG_PASSWORD:      password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr

  kong:
    image: kong_oidc:1.0-SNAPSHOT
    init: true
    restart: on-failure
    depends_on:
      - kong-migration
    networks:
      - kong-net
    ports:
      - "8000:8000" # Listener
      - "8001:8001" # Admin API
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          kong-db
      KONG_PG_PORT:          5432
      KONG_PG_DATABASE:      kong
      KONG_PG_USER:          kong
      KONG_PG_PASSWORD:      password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr
      KONG_PROXY_LISTEN:     0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN:     0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS:          oidc

  keycloak-db:
    image: postgres:9.6-alpine
    init: true
    restart: on-failure
    volumes:
      - keycloak-datastore:/var/lib/postgresql/data
    networks:
      - kong-net
    environment:
      POSTGRES_DB:       keycloak
      POSTGRES_USER:     keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak:4.8.3.Final
    init: true
    restart: on-failure
    depends_on:
      - keycloak-db
    networks:
      - kong-net
    ports:
      - "8180:8080"
    environment:
      DB_VENDOR:         POSTGRES
      DB_ADDR:           keycloak-db
      DB_PORT:           5432
      DB_DATABASE:       keycloak
      DB_USER:           keycloak
      DB_PASSWORD:       password
      KEYCLOAK_USER:     admin
      KEYCLOAK_PASSWORD: admin

  echo:
    image: echo:1.0-SNAPSHOT
    init: true
    depends_on:
      - kong
    networks:
      - kong-net
