version: '3.7'

networks:
  kong-net:

volumes:
  kong-datastore:
  keycloak-datastore:

services:
  kong-db:
    image: postgres:9.6-alpine
    init: true
    restart: on-failure
    volumes:
      - kong-datastore:/var/lib/postgresql/data
    networks:
      - kong-net
    environment:
      POSTGRES_DB:       kong
      POSTGRES_USER:     kong
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3

  kong-migration:
    image: kong_oidc
    init: true
    depends_on:
      - kong-db
    command: kong migrations bootstrap
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          kong-db
      KONG_PG_PORT:          5432
      KONG_PG_DATABASE:      kong
      KONG_PG_USER:          kong
      KONG_PG_PASSWORD:      password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr

  kong:
    image: kong_oidc
    init: true
    restart: on-failure
    depends_on:
      - kong-migration
    networks:
      - kong-net
    ports:
      - "8000:8000" # Listener
      - "8001:8001" # Admin API
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          kong-db
      KONG_PG_PORT:          5432
      KONG_PG_DATABASE:      kong
      KONG_PG_USER:          kong
      KONG_PG_PASSWORD:      password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr
      KONG_PROXY_LISTEN:     0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN:     0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS:          oidc
      KONG_NGINX_PROXY_SET: "$$session_secret c2VjcmV0VmVyeVNlY3VyZQ=="

  konga:
    image: pantsel/konga:0.14.7
    init: true
    restart: unless-stopped
    depends_on:
      - kong
    networks:
      - kong-net
    ports:
      - "8280:1337"
    environment:
      DB_ADAPTER: "postgres"
      DB_URI: "postgresql://kong:password@kong-db:5432/kong"
      KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE: "/home/conf/kong_node.js"
      KONGA_SEED_USER_DATA_SOURCE_FILE: "/home/conf/users.js"
    volumes:
      - ./src/main/configuration/konga/:/home/conf/:ro

  keycloak-db:
    image: postgres:9.6-alpine
    init: true
    restart: on-failure
    volumes:
      - keycloak-datastore:/var/lib/postgresql/data
    networks:
      - kong-net
    environment:
      POSTGRES_DB:       keycloak
      POSTGRES_USER:     keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak:9.0.0
    init: true
    restart: on-failure
    depends_on:
      - keycloak-db
    networks:
      - kong-net
    ports:
      - "8180:8080"
    environment:
      DB_VENDOR:         POSTGRES
      DB_ADDR:           keycloak-db
      DB_PORT:           5432
      DB_DATABASE:       keycloak
      DB_USER:           keycloak
      DB_PASSWORD:       password
      KEYCLOAK_USER:     admin
      KEYCLOAK_PASSWORD: admin123

  demo-configuration:
    image: curl_jq
    init: true
    restart: on-failure
    depends_on:
      - keycloak
      - kong
    networks:
      - kong-net
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin123
      - HOST_IP
    entrypoint: /home/conf/configure.sh
    volumes:
      - ./src/main/configuration/gateway:/home/conf/:ro

  echo:
    image: echo
    init: true
    depends_on:
      - kong
    networks:
      - kong-net
